# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://github.com/Ezard/semantic-prs#configuration-options
# The values allowed for the "type" part of the PR title/commit message. e.g. for a PR title/commit message of "feat: add some stuff", the type would be "feat"
# The merged commit will trigger semantic release actions governed by https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js
types: # default: feat | fix | docs | style | refactor | perf | test | build | ci | chore | revert
  - build # Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
  - chore # Other changes that do not affect the developer interface
  - docs # Documentation only changes, triggers PATCH version release
  - feat # A new feature, triggers MINOR version release
  - fix #  A bug fix, triggers PATCH version release
  - perf # A code change that improves performance, triggers PATCH version release
  - refactor # A code change that neither fixes a bug nor adds a feature
  - revert # Reverts a previous commit

# Allows a custom URL for the "Details" link (which appears next to the success/failure message from the app) to be specified
targetUrl: https://github.com/googlemaps/.github/blob/master/.github/semantic.yml # default: https://github.com/Ezard/semantic-prs
