group:
  # JavaScript files
  - files:
      - source: sync-files/js/.github/
        dest: .github/
        exclude: |
          workflows/bundlewatch.yml
          bundlewatch.config.json
      - source: sync-files/js/.eslintignore
        dest: .eslintignore
      - source: sync-files/js/.eslintrc.json
        dest: .eslintrc.json
      - source: sync-files/js/.releaserc
        dest: .releaserc
    repos: |
      googlemaps/js-api-loader
      googlemaps/js-jest-mocks
      googlemaps/js-markerclusterer
      googlemaps/js-markerclustererplus
      googlemaps/js-markermanager
      googlemaps/js-markerwithlabel
      googlemaps/js-ogc
      googlemaps/js-polyline-codec
      googlemaps/js-three
      googlemaps/react-wrapper
  # Browser only JavaScript files
  - files:
      - source: sync-files/js/.github/
        dest: .github/
      - source: sync-files/js/.babelrc
        dest: .babelrc
    repos: |
      googlemaps/js-api-loader
      googlemaps/js-markerclusterer
      googlemaps/js-markerclustererplus
      googlemaps/js-markermanager
      googlemaps/js-markerwithlabel
      googlemaps/js-ogc
      googlemaps/js-polyline-codec
      googlemaps/js-three
  # Add SECURITY.md to all repositories
  - files:
      - source: SECURITY.md
        dest: SECURITY.md
    # gh repo list googlemaps --public --source --no-archived  --json name | jq '.[] | .name'
    repos: |
      googlemaps/.github
      googlemaps/android-v3-migration
      googlemaps/android-maps-ktx
      googlemaps/android-maps-rx
      googlemaps/android-maps-utils
      googlemaps/android-on-demand-rides-deliveries-samples
      googlemaps/android-places-demos
      googlemaps/android-places-ktx
      googlemaps/android-samples
      googlemaps/deck.gl-demos
      googlemaps/go-routespreferred
      googlemaps/google-maps-ios-utils
      googlemaps/google-maps-services-java
      googlemaps/google-maps-services-js
      googlemaps/google-maps-services-python
      googlemaps/js-api-loader
      googlemaps/js-jest-mocks
      googlemaps/js-markerclusterer
      googlemaps/js-markerclustererplus
      googlemaps/js-markermanager
      googlemaps/js-markerwithlabel
      googlemaps/js-ogc
      googlemaps/js-polyline-codec
      googlemaps/js-samples
      googlemaps/js-three
      googlemaps/js-types
      googlemaps/maps-sdk-for-ios-samples
      googlemaps/openapi-specification
      googlemaps/playablelocations-proxy
      googlemaps/react-wrapper
      googlemaps/semantic-release-config
  # Android Library files (Groovy)
  - files:
      - source: sync-files/android/.github/
        dest: .github/
      - source: sync-files/android/.lib_releaserc_groovy
        dest: .releaserc
    repos: |
      googlemaps/android-maps-ktx
      googlemaps/android-maps-utils
      googlemaps/android-places-ktx
  # Android Library files (KTS)
  - files:
      - source: sync-files/android/.github/
        dest: .github/
      - source: sync-files/android/.lib_releaserc_kts
        dest: .releaserc
    repos: |
      googlemaps/android-maps-rx
  # Android Plugins
  - files:
      - source: sync-files/android/.github/
        dest: .github/
        exclude: |
          workflows/release.yml
      - source: sync-files/android/.plugin_releaserc
        dest: .releaserc
    repos: |
      googlemaps/android-v3-migration
