// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/compute_routes_response.proto

package com.google.maps.routes.v1;

public final class ComputeRoutesResponseProto {
  private ComputeRoutesResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_maps_routes_v1_ComputeRoutesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_routes_v1_ComputeRoutesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3google/maps/routes/v1/compute_routes_r" +
      "esponse.proto\022\025google.maps.routes.v1\032)go" +
      "ogle/maps/routes/v1/fallback_info.proto\032" +
      "!google/maps/routes/v1/route.proto\"\201\001\n\025C" +
      "omputeRoutesResponse\022,\n\006routes\030\001 \003(\0132\034.g" +
      "oogle.maps.routes.v1.Route\022:\n\rfallback_i" +
      "nfo\030\002 \001(\0132#.google.maps.routes.v1.Fallba" +
      "ckInfoB\260\001\n\031com.google.maps.routes.v1B\032Co" +
      "mputeRoutesResponseProtoP\001Z;google.golan" +
      "g.org/genproto/googleapis/maps/routes/v1" +
      ";routes\370\001\001\242\002\004GMRS\252\002\025Google.Maps.Routes.V" +
      "1\312\002\025Google\\Maps\\Routes\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.maps.routes.v1.FallbackInfoProto.getDescriptor(),
          com.google.maps.routes.v1.RouteProto.getDescriptor(),
        });
    internal_static_google_maps_routes_v1_ComputeRoutesResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_maps_routes_v1_ComputeRoutesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_maps_routes_v1_ComputeRoutesResponse_descriptor,
        new java.lang.String[] { "Routes", "FallbackInfo", });
    com.google.maps.routes.v1.FallbackInfoProto.getDescriptor();
    com.google.maps.routes.v1.RouteProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
