// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/route.proto

package com.google.maps.routes.v1;

/**
 * <pre>
 * Encapsulates the license plate last character restriction.
 * </pre>
 *
 * Protobuf type {@code google.maps.routes.v1.LicensePlateLastCharacterRestriction}
 */
public  final class LicensePlateLastCharacterRestriction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.maps.routes.v1.LicensePlateLastCharacterRestriction)
    LicensePlateLastCharacterRestrictionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LicensePlateLastCharacterRestriction.newBuilder() to construct.
  private LicensePlateLastCharacterRestriction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LicensePlateLastCharacterRestriction() {
    allowedLastCharacters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LicensePlateLastCharacterRestriction();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LicensePlateLastCharacterRestriction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              allowedLastCharacters_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            allowedLastCharacters_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        allowedLastCharacters_ = allowedLastCharacters_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_LicensePlateLastCharacterRestriction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_LicensePlateLastCharacterRestriction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.class, com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.Builder.class);
  }

  public static final int ALLOWED_LAST_CHARACTERS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList allowedLastCharacters_;
  /**
   * <pre>
   * The allowed last character of a license plate of a vehicle. Only vehicles
   * whose license plate's last characters match these are allowed to travel on
   * the route. If empty, no vehicle is allowed.
   * </pre>
   *
   * <code>repeated string allowed_last_characters = 1;</code>
   * @return A list containing the allowedLastCharacters.
   */
  public com.google.protobuf.ProtocolStringList
      getAllowedLastCharactersList() {
    return allowedLastCharacters_;
  }
  /**
   * <pre>
   * The allowed last character of a license plate of a vehicle. Only vehicles
   * whose license plate's last characters match these are allowed to travel on
   * the route. If empty, no vehicle is allowed.
   * </pre>
   *
   * <code>repeated string allowed_last_characters = 1;</code>
   * @return The count of allowedLastCharacters.
   */
  public int getAllowedLastCharactersCount() {
    return allowedLastCharacters_.size();
  }
  /**
   * <pre>
   * The allowed last character of a license plate of a vehicle. Only vehicles
   * whose license plate's last characters match these are allowed to travel on
   * the route. If empty, no vehicle is allowed.
   * </pre>
   *
   * <code>repeated string allowed_last_characters = 1;</code>
   * @param index The index of the element to return.
   * @return The allowedLastCharacters at the given index.
   */
  public java.lang.String getAllowedLastCharacters(int index) {
    return allowedLastCharacters_.get(index);
  }
  /**
   * <pre>
   * The allowed last character of a license plate of a vehicle. Only vehicles
   * whose license plate's last characters match these are allowed to travel on
   * the route. If empty, no vehicle is allowed.
   * </pre>
   *
   * <code>repeated string allowed_last_characters = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the allowedLastCharacters at the given index.
   */
  public com.google.protobuf.ByteString
      getAllowedLastCharactersBytes(int index) {
    return allowedLastCharacters_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < allowedLastCharacters_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, allowedLastCharacters_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < allowedLastCharacters_.size(); i++) {
        dataSize += computeStringSizeNoTag(allowedLastCharacters_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAllowedLastCharactersList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.maps.routes.v1.LicensePlateLastCharacterRestriction)) {
      return super.equals(obj);
    }
    com.google.maps.routes.v1.LicensePlateLastCharacterRestriction other = (com.google.maps.routes.v1.LicensePlateLastCharacterRestriction) obj;

    if (!getAllowedLastCharactersList()
        .equals(other.getAllowedLastCharactersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAllowedLastCharactersCount() > 0) {
      hash = (37 * hash) + ALLOWED_LAST_CHARACTERS_FIELD_NUMBER;
      hash = (53 * hash) + getAllowedLastCharactersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.maps.routes.v1.LicensePlateLastCharacterRestriction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Encapsulates the license plate last character restriction.
   * </pre>
   *
   * Protobuf type {@code google.maps.routes.v1.LicensePlateLastCharacterRestriction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.maps.routes.v1.LicensePlateLastCharacterRestriction)
      com.google.maps.routes.v1.LicensePlateLastCharacterRestrictionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_LicensePlateLastCharacterRestriction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_LicensePlateLastCharacterRestriction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.class, com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.Builder.class);
    }

    // Construct using com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      allowedLastCharacters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_LicensePlateLastCharacterRestriction_descriptor;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.LicensePlateLastCharacterRestriction getDefaultInstanceForType() {
      return com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.maps.routes.v1.LicensePlateLastCharacterRestriction build() {
      com.google.maps.routes.v1.LicensePlateLastCharacterRestriction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.LicensePlateLastCharacterRestriction buildPartial() {
      com.google.maps.routes.v1.LicensePlateLastCharacterRestriction result = new com.google.maps.routes.v1.LicensePlateLastCharacterRestriction(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        allowedLastCharacters_ = allowedLastCharacters_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.allowedLastCharacters_ = allowedLastCharacters_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.maps.routes.v1.LicensePlateLastCharacterRestriction) {
        return mergeFrom((com.google.maps.routes.v1.LicensePlateLastCharacterRestriction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.maps.routes.v1.LicensePlateLastCharacterRestriction other) {
      if (other == com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.getDefaultInstance()) return this;
      if (!other.allowedLastCharacters_.isEmpty()) {
        if (allowedLastCharacters_.isEmpty()) {
          allowedLastCharacters_ = other.allowedLastCharacters_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAllowedLastCharactersIsMutable();
          allowedLastCharacters_.addAll(other.allowedLastCharacters_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.maps.routes.v1.LicensePlateLastCharacterRestriction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.maps.routes.v1.LicensePlateLastCharacterRestriction) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList allowedLastCharacters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAllowedLastCharactersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        allowedLastCharacters_ = new com.google.protobuf.LazyStringArrayList(allowedLastCharacters_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * The allowed last character of a license plate of a vehicle. Only vehicles
     * whose license plate's last characters match these are allowed to travel on
     * the route. If empty, no vehicle is allowed.
     * </pre>
     *
     * <code>repeated string allowed_last_characters = 1;</code>
     * @return A list containing the allowedLastCharacters.
     */
    public com.google.protobuf.ProtocolStringList
        getAllowedLastCharactersList() {
      return allowedLastCharacters_.getUnmodifiableView();
    }
    /**
     * <pre>
     * The allowed last character of a license plate of a vehicle. Only vehicles
     * whose license plate's last characters match these are allowed to travel on
     * the route. If empty, no vehicle is allowed.
     * </pre>
     *
     * <code>repeated string allowed_last_characters = 1;</code>
     * @return The count of allowedLastCharacters.
     */
    public int getAllowedLastCharactersCount() {
      return allowedLastCharacters_.size();
    }
    /**
     * <pre>
     * The allowed last character of a license plate of a vehicle. Only vehicles
     * whose license plate's last characters match these are allowed to travel on
     * the route. If empty, no vehicle is allowed.
     * </pre>
     *
     * <code>repeated string allowed_last_characters = 1;</code>
     * @param index The index of the element to return.
     * @return The allowedLastCharacters at the given index.
     */
    public java.lang.String getAllowedLastCharacters(int index) {
      return allowedLastCharacters_.get(index);
    }
    /**
     * <pre>
     * The allowed last character of a license plate of a vehicle. Only vehicles
     * whose license plate's last characters match these are allowed to travel on
     * the route. If empty, no vehicle is allowed.
     * </pre>
     *
     * <code>repeated string allowed_last_characters = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the allowedLastCharacters at the given index.
     */
    public com.google.protobuf.ByteString
        getAllowedLastCharactersBytes(int index) {
      return allowedLastCharacters_.getByteString(index);
    }
    /**
     * <pre>
     * The allowed last character of a license plate of a vehicle. Only vehicles
     * whose license plate's last characters match these are allowed to travel on
     * the route. If empty, no vehicle is allowed.
     * </pre>
     *
     * <code>repeated string allowed_last_characters = 1;</code>
     * @param index The index to set the value at.
     * @param value The allowedLastCharacters to set.
     * @return This builder for chaining.
     */
    public Builder setAllowedLastCharacters(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAllowedLastCharactersIsMutable();
      allowedLastCharacters_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The allowed last character of a license plate of a vehicle. Only vehicles
     * whose license plate's last characters match these are allowed to travel on
     * the route. If empty, no vehicle is allowed.
     * </pre>
     *
     * <code>repeated string allowed_last_characters = 1;</code>
     * @param value The allowedLastCharacters to add.
     * @return This builder for chaining.
     */
    public Builder addAllowedLastCharacters(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAllowedLastCharactersIsMutable();
      allowedLastCharacters_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The allowed last character of a license plate of a vehicle. Only vehicles
     * whose license plate's last characters match these are allowed to travel on
     * the route. If empty, no vehicle is allowed.
     * </pre>
     *
     * <code>repeated string allowed_last_characters = 1;</code>
     * @param values The allowedLastCharacters to add.
     * @return This builder for chaining.
     */
    public Builder addAllAllowedLastCharacters(
        java.lang.Iterable<java.lang.String> values) {
      ensureAllowedLastCharactersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, allowedLastCharacters_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The allowed last character of a license plate of a vehicle. Only vehicles
     * whose license plate's last characters match these are allowed to travel on
     * the route. If empty, no vehicle is allowed.
     * </pre>
     *
     * <code>repeated string allowed_last_characters = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowedLastCharacters() {
      allowedLastCharacters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The allowed last character of a license plate of a vehicle. Only vehicles
     * whose license plate's last characters match these are allowed to travel on
     * the route. If empty, no vehicle is allowed.
     * </pre>
     *
     * <code>repeated string allowed_last_characters = 1;</code>
     * @param value The bytes of the allowedLastCharacters to add.
     * @return This builder for chaining.
     */
    public Builder addAllowedLastCharactersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAllowedLastCharactersIsMutable();
      allowedLastCharacters_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.maps.routes.v1.LicensePlateLastCharacterRestriction)
  }

  // @@protoc_insertion_point(class_scope:google.maps.routes.v1.LicensePlateLastCharacterRestriction)
  private static final com.google.maps.routes.v1.LicensePlateLastCharacterRestriction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.maps.routes.v1.LicensePlateLastCharacterRestriction();
  }

  public static com.google.maps.routes.v1.LicensePlateLastCharacterRestriction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LicensePlateLastCharacterRestriction>
      PARSER = new com.google.protobuf.AbstractParser<LicensePlateLastCharacterRestriction>() {
    @java.lang.Override
    public LicensePlateLastCharacterRestriction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LicensePlateLastCharacterRestriction(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LicensePlateLastCharacterRestriction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LicensePlateLastCharacterRestriction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.maps.routes.v1.LicensePlateLastCharacterRestriction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

