// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/polyline.proto

package com.google.maps.routes.v1;

public interface PolylineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.maps.routes.v1.Polyline)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The string encoding of the polyline using the [polyline encoding
   * algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
   * </pre>
   *
   * <code>string encoded_polyline = 1;</code>
   * @return The encodedPolyline.
   */
  java.lang.String getEncodedPolyline();
  /**
   * <pre>
   * The string encoding of the polyline using the [polyline encoding
   * algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
   * </pre>
   *
   * <code>string encoded_polyline = 1;</code>
   * @return The bytes for encodedPolyline.
   */
  com.google.protobuf.ByteString
      getEncodedPolylineBytes();

  public com.google.maps.routes.v1.Polyline.PolylineTypeCase getPolylineTypeCase();
}
