// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/polyline.proto

package com.google.maps.routes.v1;

/**
 * <pre>
 * Encapsulates an encoded polyline.
 * </pre>
 *
 * Protobuf type {@code google.maps.routes.v1.Polyline}
 */
public  final class Polyline extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.maps.routes.v1.Polyline)
    PolylineOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Polyline.newBuilder() to construct.
  private Polyline(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Polyline() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Polyline();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Polyline(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            polylineTypeCase_ = 1;
            polylineType_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.maps.routes.v1.PolylineProto.internal_static_google_maps_routes_v1_Polyline_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.maps.routes.v1.PolylineProto.internal_static_google_maps_routes_v1_Polyline_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.maps.routes.v1.Polyline.class, com.google.maps.routes.v1.Polyline.Builder.class);
  }

  private int polylineTypeCase_ = 0;
  private java.lang.Object polylineType_;
  public enum PolylineTypeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ENCODED_POLYLINE(1),
    POLYLINETYPE_NOT_SET(0);
    private final int value;
    private PolylineTypeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PolylineTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static PolylineTypeCase forNumber(int value) {
      switch (value) {
        case 1: return ENCODED_POLYLINE;
        case 0: return POLYLINETYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PolylineTypeCase
  getPolylineTypeCase() {
    return PolylineTypeCase.forNumber(
        polylineTypeCase_);
  }

  public static final int ENCODED_POLYLINE_FIELD_NUMBER = 1;
  /**
   * <pre>
   * The string encoding of the polyline using the [polyline encoding
   * algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
   * </pre>
   *
   * <code>string encoded_polyline = 1;</code>
   * @return The encodedPolyline.
   */
  public java.lang.String getEncodedPolyline() {
    java.lang.Object ref = "";
    if (polylineTypeCase_ == 1) {
      ref = polylineType_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (polylineTypeCase_ == 1) {
        polylineType_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The string encoding of the polyline using the [polyline encoding
   * algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
   * </pre>
   *
   * <code>string encoded_polyline = 1;</code>
   * @return The bytes for encodedPolyline.
   */
  public com.google.protobuf.ByteString
      getEncodedPolylineBytes() {
    java.lang.Object ref = "";
    if (polylineTypeCase_ == 1) {
      ref = polylineType_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (polylineTypeCase_ == 1) {
        polylineType_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (polylineTypeCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, polylineType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (polylineTypeCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, polylineType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.maps.routes.v1.Polyline)) {
      return super.equals(obj);
    }
    com.google.maps.routes.v1.Polyline other = (com.google.maps.routes.v1.Polyline) obj;

    if (!getPolylineTypeCase().equals(other.getPolylineTypeCase())) return false;
    switch (polylineTypeCase_) {
      case 1:
        if (!getEncodedPolyline()
            .equals(other.getEncodedPolyline())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (polylineTypeCase_) {
      case 1:
        hash = (37 * hash) + ENCODED_POLYLINE_FIELD_NUMBER;
        hash = (53 * hash) + getEncodedPolyline().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.maps.routes.v1.Polyline parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.Polyline parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.Polyline parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.Polyline parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.Polyline parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.Polyline parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.Polyline parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.Polyline parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.Polyline parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.Polyline parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.Polyline parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.Polyline parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.maps.routes.v1.Polyline prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Encapsulates an encoded polyline.
   * </pre>
   *
   * Protobuf type {@code google.maps.routes.v1.Polyline}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.maps.routes.v1.Polyline)
      com.google.maps.routes.v1.PolylineOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.maps.routes.v1.PolylineProto.internal_static_google_maps_routes_v1_Polyline_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.maps.routes.v1.PolylineProto.internal_static_google_maps_routes_v1_Polyline_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.maps.routes.v1.Polyline.class, com.google.maps.routes.v1.Polyline.Builder.class);
    }

    // Construct using com.google.maps.routes.v1.Polyline.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      polylineTypeCase_ = 0;
      polylineType_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.maps.routes.v1.PolylineProto.internal_static_google_maps_routes_v1_Polyline_descriptor;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.Polyline getDefaultInstanceForType() {
      return com.google.maps.routes.v1.Polyline.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.maps.routes.v1.Polyline build() {
      com.google.maps.routes.v1.Polyline result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.Polyline buildPartial() {
      com.google.maps.routes.v1.Polyline result = new com.google.maps.routes.v1.Polyline(this);
      if (polylineTypeCase_ == 1) {
        result.polylineType_ = polylineType_;
      }
      result.polylineTypeCase_ = polylineTypeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.maps.routes.v1.Polyline) {
        return mergeFrom((com.google.maps.routes.v1.Polyline)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.maps.routes.v1.Polyline other) {
      if (other == com.google.maps.routes.v1.Polyline.getDefaultInstance()) return this;
      switch (other.getPolylineTypeCase()) {
        case ENCODED_POLYLINE: {
          polylineTypeCase_ = 1;
          polylineType_ = other.polylineType_;
          onChanged();
          break;
        }
        case POLYLINETYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.maps.routes.v1.Polyline parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.maps.routes.v1.Polyline) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int polylineTypeCase_ = 0;
    private java.lang.Object polylineType_;
    public PolylineTypeCase
        getPolylineTypeCase() {
      return PolylineTypeCase.forNumber(
          polylineTypeCase_);
    }

    public Builder clearPolylineType() {
      polylineTypeCase_ = 0;
      polylineType_ = null;
      onChanged();
      return this;
    }


    /**
     * <pre>
     * The string encoding of the polyline using the [polyline encoding
     * algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
     * </pre>
     *
     * <code>string encoded_polyline = 1;</code>
     * @return The encodedPolyline.
     */
    public java.lang.String getEncodedPolyline() {
      java.lang.Object ref = "";
      if (polylineTypeCase_ == 1) {
        ref = polylineType_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (polylineTypeCase_ == 1) {
          polylineType_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The string encoding of the polyline using the [polyline encoding
     * algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
     * </pre>
     *
     * <code>string encoded_polyline = 1;</code>
     * @return The bytes for encodedPolyline.
     */
    public com.google.protobuf.ByteString
        getEncodedPolylineBytes() {
      java.lang.Object ref = "";
      if (polylineTypeCase_ == 1) {
        ref = polylineType_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (polylineTypeCase_ == 1) {
          polylineType_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The string encoding of the polyline using the [polyline encoding
     * algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
     * </pre>
     *
     * <code>string encoded_polyline = 1;</code>
     * @param value The encodedPolyline to set.
     * @return This builder for chaining.
     */
    public Builder setEncodedPolyline(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  polylineTypeCase_ = 1;
      polylineType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The string encoding of the polyline using the [polyline encoding
     * algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
     * </pre>
     *
     * <code>string encoded_polyline = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncodedPolyline() {
      if (polylineTypeCase_ == 1) {
        polylineTypeCase_ = 0;
        polylineType_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The string encoding of the polyline using the [polyline encoding
     * algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
     * </pre>
     *
     * <code>string encoded_polyline = 1;</code>
     * @param value The bytes for encodedPolyline to set.
     * @return This builder for chaining.
     */
    public Builder setEncodedPolylineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      polylineTypeCase_ = 1;
      polylineType_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.maps.routes.v1.Polyline)
  }

  // @@protoc_insertion_point(class_scope:google.maps.routes.v1.Polyline)
  private static final com.google.maps.routes.v1.Polyline DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.maps.routes.v1.Polyline();
  }

  public static com.google.maps.routes.v1.Polyline getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Polyline>
      PARSER = new com.google.protobuf.AbstractParser<Polyline>() {
    @java.lang.Override
    public Polyline parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Polyline(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Polyline> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Polyline> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.maps.routes.v1.Polyline getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

