// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/route_matrix_element.proto

package com.google.maps.routes.v1;

/**
 * <pre>
 * Encapsulates route information computed for an origin/destination pair in the
 * ComputeRouteMatrix API. This proto can be streamed to the client.
 * </pre>
 *
 * Protobuf type {@code google.maps.routes.v1.RouteMatrixElement}
 */
public  final class RouteMatrixElement extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.maps.routes.v1.RouteMatrixElement)
    RouteMatrixElementOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RouteMatrixElement.newBuilder() to construct.
  private RouteMatrixElement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RouteMatrixElement() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RouteMatrixElement();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RouteMatrixElement(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            originIndex_ = input.readInt32();
            break;
          }
          case 16: {

            destinationIndex_ = input.readInt32();
            break;
          }
          case 26: {
            com.google.rpc.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(com.google.rpc.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            distanceMeters_ = input.readInt32();
            break;
          }
          case 42: {
            com.google.protobuf.Duration.Builder subBuilder = null;
            if (duration_ != null) {
              subBuilder = duration_.toBuilder();
            }
            duration_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(duration_);
              duration_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.Duration.Builder subBuilder = null;
            if (staticDuration_ != null) {
              subBuilder = staticDuration_.toBuilder();
            }
            staticDuration_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(staticDuration_);
              staticDuration_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.maps.routes.v1.RouteTravelAdvisory.Builder subBuilder = null;
            if (travelAdvisory_ != null) {
              subBuilder = travelAdvisory_.toBuilder();
            }
            travelAdvisory_ = input.readMessage(com.google.maps.routes.v1.RouteTravelAdvisory.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(travelAdvisory_);
              travelAdvisory_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.maps.routes.v1.FallbackInfo.Builder subBuilder = null;
            if (fallbackInfo_ != null) {
              subBuilder = fallbackInfo_.toBuilder();
            }
            fallbackInfo_ = input.readMessage(com.google.maps.routes.v1.FallbackInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fallbackInfo_);
              fallbackInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.maps.routes.v1.ComputeRouteMatrixElementProto.internal_static_google_maps_routes_v1_RouteMatrixElement_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.maps.routes.v1.ComputeRouteMatrixElementProto.internal_static_google_maps_routes_v1_RouteMatrixElement_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.maps.routes.v1.RouteMatrixElement.class, com.google.maps.routes.v1.RouteMatrixElement.Builder.class);
  }

  public static final int ORIGIN_INDEX_FIELD_NUMBER = 1;
  private int originIndex_;
  /**
   * <pre>
   * Zero-based index of the origin in the request.
   * </pre>
   *
   * <code>int32 origin_index = 1;</code>
   * @return The originIndex.
   */
  public int getOriginIndex() {
    return originIndex_;
  }

  public static final int DESTINATION_INDEX_FIELD_NUMBER = 2;
  private int destinationIndex_;
  /**
   * <pre>
   * Zero-based index of the destination in the request.
   * </pre>
   *
   * <code>int32 destination_index = 2;</code>
   * @return The destinationIndex.
   */
  public int getDestinationIndex() {
    return destinationIndex_;
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private com.google.rpc.Status status_;
  /**
   * <pre>
   * Error status code for this element.
   * </pre>
   *
   * <code>.google.rpc.Status status = 3;</code>
   * @return Whether the status field is set.
   */
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <pre>
   * Error status code for this element.
   * </pre>
   *
   * <code>.google.rpc.Status status = 3;</code>
   * @return The status.
   */
  public com.google.rpc.Status getStatus() {
    return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
  }
  /**
   * <pre>
   * Error status code for this element.
   * </pre>
   *
   * <code>.google.rpc.Status status = 3;</code>
   */
  public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int DISTANCE_METERS_FIELD_NUMBER = 4;
  private int distanceMeters_;
  /**
   * <pre>
   * The travel distance of the route, in meters.
   * </pre>
   *
   * <code>int32 distance_meters = 4;</code>
   * @return The distanceMeters.
   */
  public int getDistanceMeters() {
    return distanceMeters_;
  }

  public static final int DURATION_FIELD_NUMBER = 5;
  private com.google.protobuf.Duration duration_;
  /**
   * <pre>
   * The length of time needed to navigate the route. If you set the
   * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
   * `static_duration`. If you set the `route_preference` to either
   * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
   * taking traffic conditions into account.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 5;</code>
   * @return Whether the duration field is set.
   */
  public boolean hasDuration() {
    return duration_ != null;
  }
  /**
   * <pre>
   * The length of time needed to navigate the route. If you set the
   * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
   * `static_duration`. If you set the `route_preference` to either
   * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
   * taking traffic conditions into account.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 5;</code>
   * @return The duration.
   */
  public com.google.protobuf.Duration getDuration() {
    return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
  }
  /**
   * <pre>
   * The length of time needed to navigate the route. If you set the
   * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
   * `static_duration`. If you set the `route_preference` to either
   * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
   * taking traffic conditions into account.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 5;</code>
   */
  public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
    return getDuration();
  }

  public static final int STATIC_DURATION_FIELD_NUMBER = 6;
  private com.google.protobuf.Duration staticDuration_;
  /**
   * <pre>
   * The duration of traveling through the route without taking traffic
   * conditions into consideration.
   * </pre>
   *
   * <code>.google.protobuf.Duration static_duration = 6;</code>
   * @return Whether the staticDuration field is set.
   */
  public boolean hasStaticDuration() {
    return staticDuration_ != null;
  }
  /**
   * <pre>
   * The duration of traveling through the route without taking traffic
   * conditions into consideration.
   * </pre>
   *
   * <code>.google.protobuf.Duration static_duration = 6;</code>
   * @return The staticDuration.
   */
  public com.google.protobuf.Duration getStaticDuration() {
    return staticDuration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : staticDuration_;
  }
  /**
   * <pre>
   * The duration of traveling through the route without taking traffic
   * conditions into consideration.
   * </pre>
   *
   * <code>.google.protobuf.Duration static_duration = 6;</code>
   */
  public com.google.protobuf.DurationOrBuilder getStaticDurationOrBuilder() {
    return getStaticDuration();
  }

  public static final int TRAVEL_ADVISORY_FIELD_NUMBER = 7;
  private com.google.maps.routes.v1.RouteTravelAdvisory travelAdvisory_;
  /**
   * <pre>
   * Additional information about the route. For example: restriction
   * information and toll information
   * </pre>
   *
   * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
   * @return Whether the travelAdvisory field is set.
   */
  public boolean hasTravelAdvisory() {
    return travelAdvisory_ != null;
  }
  /**
   * <pre>
   * Additional information about the route. For example: restriction
   * information and toll information
   * </pre>
   *
   * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
   * @return The travelAdvisory.
   */
  public com.google.maps.routes.v1.RouteTravelAdvisory getTravelAdvisory() {
    return travelAdvisory_ == null ? com.google.maps.routes.v1.RouteTravelAdvisory.getDefaultInstance() : travelAdvisory_;
  }
  /**
   * <pre>
   * Additional information about the route. For example: restriction
   * information and toll information
   * </pre>
   *
   * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
   */
  public com.google.maps.routes.v1.RouteTravelAdvisoryOrBuilder getTravelAdvisoryOrBuilder() {
    return getTravelAdvisory();
  }

  public static final int FALLBACK_INFO_FIELD_NUMBER = 8;
  private com.google.maps.routes.v1.FallbackInfo fallbackInfo_;
  /**
   * <pre>
   * In some cases when the server is not able to compute the route with the
   * given preferences for this particular origin/destination pair, it may
   * fall back to using a different mode of computation. When fallback mode is
   * used, this field contains detailed information about the fallback response.
   * Otherwise this field is unset.
   * </pre>
   *
   * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
   * @return Whether the fallbackInfo field is set.
   */
  public boolean hasFallbackInfo() {
    return fallbackInfo_ != null;
  }
  /**
   * <pre>
   * In some cases when the server is not able to compute the route with the
   * given preferences for this particular origin/destination pair, it may
   * fall back to using a different mode of computation. When fallback mode is
   * used, this field contains detailed information about the fallback response.
   * Otherwise this field is unset.
   * </pre>
   *
   * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
   * @return The fallbackInfo.
   */
  public com.google.maps.routes.v1.FallbackInfo getFallbackInfo() {
    return fallbackInfo_ == null ? com.google.maps.routes.v1.FallbackInfo.getDefaultInstance() : fallbackInfo_;
  }
  /**
   * <pre>
   * In some cases when the server is not able to compute the route with the
   * given preferences for this particular origin/destination pair, it may
   * fall back to using a different mode of computation. When fallback mode is
   * used, this field contains detailed information about the fallback response.
   * Otherwise this field is unset.
   * </pre>
   *
   * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
   */
  public com.google.maps.routes.v1.FallbackInfoOrBuilder getFallbackInfoOrBuilder() {
    return getFallbackInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (originIndex_ != 0) {
      output.writeInt32(1, originIndex_);
    }
    if (destinationIndex_ != 0) {
      output.writeInt32(2, destinationIndex_);
    }
    if (status_ != null) {
      output.writeMessage(3, getStatus());
    }
    if (distanceMeters_ != 0) {
      output.writeInt32(4, distanceMeters_);
    }
    if (duration_ != null) {
      output.writeMessage(5, getDuration());
    }
    if (staticDuration_ != null) {
      output.writeMessage(6, getStaticDuration());
    }
    if (travelAdvisory_ != null) {
      output.writeMessage(7, getTravelAdvisory());
    }
    if (fallbackInfo_ != null) {
      output.writeMessage(8, getFallbackInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (originIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, originIndex_);
    }
    if (destinationIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, destinationIndex_);
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStatus());
    }
    if (distanceMeters_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, distanceMeters_);
    }
    if (duration_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDuration());
    }
    if (staticDuration_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getStaticDuration());
    }
    if (travelAdvisory_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTravelAdvisory());
    }
    if (fallbackInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getFallbackInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.maps.routes.v1.RouteMatrixElement)) {
      return super.equals(obj);
    }
    com.google.maps.routes.v1.RouteMatrixElement other = (com.google.maps.routes.v1.RouteMatrixElement) obj;

    if (getOriginIndex()
        != other.getOriginIndex()) return false;
    if (getDestinationIndex()
        != other.getDestinationIndex()) return false;
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (getDistanceMeters()
        != other.getDistanceMeters()) return false;
    if (hasDuration() != other.hasDuration()) return false;
    if (hasDuration()) {
      if (!getDuration()
          .equals(other.getDuration())) return false;
    }
    if (hasStaticDuration() != other.hasStaticDuration()) return false;
    if (hasStaticDuration()) {
      if (!getStaticDuration()
          .equals(other.getStaticDuration())) return false;
    }
    if (hasTravelAdvisory() != other.hasTravelAdvisory()) return false;
    if (hasTravelAdvisory()) {
      if (!getTravelAdvisory()
          .equals(other.getTravelAdvisory())) return false;
    }
    if (hasFallbackInfo() != other.hasFallbackInfo()) return false;
    if (hasFallbackInfo()) {
      if (!getFallbackInfo()
          .equals(other.getFallbackInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORIGIN_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getOriginIndex();
    hash = (37 * hash) + DESTINATION_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationIndex();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (37 * hash) + DISTANCE_METERS_FIELD_NUMBER;
    hash = (53 * hash) + getDistanceMeters();
    if (hasDuration()) {
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration().hashCode();
    }
    if (hasStaticDuration()) {
      hash = (37 * hash) + STATIC_DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getStaticDuration().hashCode();
    }
    if (hasTravelAdvisory()) {
      hash = (37 * hash) + TRAVEL_ADVISORY_FIELD_NUMBER;
      hash = (53 * hash) + getTravelAdvisory().hashCode();
    }
    if (hasFallbackInfo()) {
      hash = (37 * hash) + FALLBACK_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getFallbackInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.RouteMatrixElement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.maps.routes.v1.RouteMatrixElement prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Encapsulates route information computed for an origin/destination pair in the
   * ComputeRouteMatrix API. This proto can be streamed to the client.
   * </pre>
   *
   * Protobuf type {@code google.maps.routes.v1.RouteMatrixElement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.maps.routes.v1.RouteMatrixElement)
      com.google.maps.routes.v1.RouteMatrixElementOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.maps.routes.v1.ComputeRouteMatrixElementProto.internal_static_google_maps_routes_v1_RouteMatrixElement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.maps.routes.v1.ComputeRouteMatrixElementProto.internal_static_google_maps_routes_v1_RouteMatrixElement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.maps.routes.v1.RouteMatrixElement.class, com.google.maps.routes.v1.RouteMatrixElement.Builder.class);
    }

    // Construct using com.google.maps.routes.v1.RouteMatrixElement.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      originIndex_ = 0;

      destinationIndex_ = 0;

      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      distanceMeters_ = 0;

      if (durationBuilder_ == null) {
        duration_ = null;
      } else {
        duration_ = null;
        durationBuilder_ = null;
      }
      if (staticDurationBuilder_ == null) {
        staticDuration_ = null;
      } else {
        staticDuration_ = null;
        staticDurationBuilder_ = null;
      }
      if (travelAdvisoryBuilder_ == null) {
        travelAdvisory_ = null;
      } else {
        travelAdvisory_ = null;
        travelAdvisoryBuilder_ = null;
      }
      if (fallbackInfoBuilder_ == null) {
        fallbackInfo_ = null;
      } else {
        fallbackInfo_ = null;
        fallbackInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.maps.routes.v1.ComputeRouteMatrixElementProto.internal_static_google_maps_routes_v1_RouteMatrixElement_descriptor;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.RouteMatrixElement getDefaultInstanceForType() {
      return com.google.maps.routes.v1.RouteMatrixElement.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.maps.routes.v1.RouteMatrixElement build() {
      com.google.maps.routes.v1.RouteMatrixElement result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.RouteMatrixElement buildPartial() {
      com.google.maps.routes.v1.RouteMatrixElement result = new com.google.maps.routes.v1.RouteMatrixElement(this);
      result.originIndex_ = originIndex_;
      result.destinationIndex_ = destinationIndex_;
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      result.distanceMeters_ = distanceMeters_;
      if (durationBuilder_ == null) {
        result.duration_ = duration_;
      } else {
        result.duration_ = durationBuilder_.build();
      }
      if (staticDurationBuilder_ == null) {
        result.staticDuration_ = staticDuration_;
      } else {
        result.staticDuration_ = staticDurationBuilder_.build();
      }
      if (travelAdvisoryBuilder_ == null) {
        result.travelAdvisory_ = travelAdvisory_;
      } else {
        result.travelAdvisory_ = travelAdvisoryBuilder_.build();
      }
      if (fallbackInfoBuilder_ == null) {
        result.fallbackInfo_ = fallbackInfo_;
      } else {
        result.fallbackInfo_ = fallbackInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.maps.routes.v1.RouteMatrixElement) {
        return mergeFrom((com.google.maps.routes.v1.RouteMatrixElement)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.maps.routes.v1.RouteMatrixElement other) {
      if (other == com.google.maps.routes.v1.RouteMatrixElement.getDefaultInstance()) return this;
      if (other.getOriginIndex() != 0) {
        setOriginIndex(other.getOriginIndex());
      }
      if (other.getDestinationIndex() != 0) {
        setDestinationIndex(other.getDestinationIndex());
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.getDistanceMeters() != 0) {
        setDistanceMeters(other.getDistanceMeters());
      }
      if (other.hasDuration()) {
        mergeDuration(other.getDuration());
      }
      if (other.hasStaticDuration()) {
        mergeStaticDuration(other.getStaticDuration());
      }
      if (other.hasTravelAdvisory()) {
        mergeTravelAdvisory(other.getTravelAdvisory());
      }
      if (other.hasFallbackInfo()) {
        mergeFallbackInfo(other.getFallbackInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.maps.routes.v1.RouteMatrixElement parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.maps.routes.v1.RouteMatrixElement) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int originIndex_ ;
    /**
     * <pre>
     * Zero-based index of the origin in the request.
     * </pre>
     *
     * <code>int32 origin_index = 1;</code>
     * @return The originIndex.
     */
    public int getOriginIndex() {
      return originIndex_;
    }
    /**
     * <pre>
     * Zero-based index of the origin in the request.
     * </pre>
     *
     * <code>int32 origin_index = 1;</code>
     * @param value The originIndex to set.
     * @return This builder for chaining.
     */
    public Builder setOriginIndex(int value) {
      
      originIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Zero-based index of the origin in the request.
     * </pre>
     *
     * <code>int32 origin_index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginIndex() {
      
      originIndex_ = 0;
      onChanged();
      return this;
    }

    private int destinationIndex_ ;
    /**
     * <pre>
     * Zero-based index of the destination in the request.
     * </pre>
     *
     * <code>int32 destination_index = 2;</code>
     * @return The destinationIndex.
     */
    public int getDestinationIndex() {
      return destinationIndex_;
    }
    /**
     * <pre>
     * Zero-based index of the destination in the request.
     * </pre>
     *
     * <code>int32 destination_index = 2;</code>
     * @param value The destinationIndex to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationIndex(int value) {
      
      destinationIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Zero-based index of the destination in the request.
     * </pre>
     *
     * <code>int32 destination_index = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationIndex() {
      
      destinationIndex_ = 0;
      onChanged();
      return this;
    }

    private com.google.rpc.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> statusBuilder_;
    /**
     * <pre>
     * Error status code for this element.
     * </pre>
     *
     * <code>.google.rpc.Status status = 3;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <pre>
     * Error status code for this element.
     * </pre>
     *
     * <code>.google.rpc.Status status = 3;</code>
     * @return The status.
     */
    public com.google.rpc.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Error status code for this element.
     * </pre>
     *
     * <code>.google.rpc.Status status = 3;</code>
     */
    public Builder setStatus(com.google.rpc.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Error status code for this element.
     * </pre>
     *
     * <code>.google.rpc.Status status = 3;</code>
     */
    public Builder setStatus(
        com.google.rpc.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Error status code for this element.
     * </pre>
     *
     * <code>.google.rpc.Status status = 3;</code>
     */
    public Builder mergeStatus(com.google.rpc.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            com.google.rpc.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Error status code for this element.
     * </pre>
     *
     * <code>.google.rpc.Status status = 3;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Error status code for this element.
     * </pre>
     *
     * <code>.google.rpc.Status status = 3;</code>
     */
    public com.google.rpc.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Error status code for this element.
     * </pre>
     *
     * <code>.google.rpc.Status status = 3;</code>
     */
    public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.google.rpc.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <pre>
     * Error status code for this element.
     * </pre>
     *
     * <code>.google.rpc.Status status = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private int distanceMeters_ ;
    /**
     * <pre>
     * The travel distance of the route, in meters.
     * </pre>
     *
     * <code>int32 distance_meters = 4;</code>
     * @return The distanceMeters.
     */
    public int getDistanceMeters() {
      return distanceMeters_;
    }
    /**
     * <pre>
     * The travel distance of the route, in meters.
     * </pre>
     *
     * <code>int32 distance_meters = 4;</code>
     * @param value The distanceMeters to set.
     * @return This builder for chaining.
     */
    public Builder setDistanceMeters(int value) {
      
      distanceMeters_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The travel distance of the route, in meters.
     * </pre>
     *
     * <code>int32 distance_meters = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistanceMeters() {
      
      distanceMeters_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Duration duration_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> durationBuilder_;
    /**
     * <pre>
     * The length of time needed to navigate the route. If you set the
     * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
     * `static_duration`. If you set the `route_preference` to either
     * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
     * taking traffic conditions into account.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 5;</code>
     * @return Whether the duration field is set.
     */
    public boolean hasDuration() {
      return durationBuilder_ != null || duration_ != null;
    }
    /**
     * <pre>
     * The length of time needed to navigate the route. If you set the
     * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
     * `static_duration`. If you set the `route_preference` to either
     * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
     * taking traffic conditions into account.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 5;</code>
     * @return The duration.
     */
    public com.google.protobuf.Duration getDuration() {
      if (durationBuilder_ == null) {
        return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
      } else {
        return durationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The length of time needed to navigate the route. If you set the
     * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
     * `static_duration`. If you set the `route_preference` to either
     * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
     * taking traffic conditions into account.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 5;</code>
     */
    public Builder setDuration(com.google.protobuf.Duration value) {
      if (durationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        duration_ = value;
        onChanged();
      } else {
        durationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The length of time needed to navigate the route. If you set the
     * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
     * `static_duration`. If you set the `route_preference` to either
     * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
     * taking traffic conditions into account.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 5;</code>
     */
    public Builder setDuration(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (durationBuilder_ == null) {
        duration_ = builderForValue.build();
        onChanged();
      } else {
        durationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The length of time needed to navigate the route. If you set the
     * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
     * `static_duration`. If you set the `route_preference` to either
     * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
     * taking traffic conditions into account.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 5;</code>
     */
    public Builder mergeDuration(com.google.protobuf.Duration value) {
      if (durationBuilder_ == null) {
        if (duration_ != null) {
          duration_ =
            com.google.protobuf.Duration.newBuilder(duration_).mergeFrom(value).buildPartial();
        } else {
          duration_ = value;
        }
        onChanged();
      } else {
        durationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The length of time needed to navigate the route. If you set the
     * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
     * `static_duration`. If you set the `route_preference` to either
     * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
     * taking traffic conditions into account.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 5;</code>
     */
    public Builder clearDuration() {
      if (durationBuilder_ == null) {
        duration_ = null;
        onChanged();
      } else {
        duration_ = null;
        durationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The length of time needed to navigate the route. If you set the
     * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
     * `static_duration`. If you set the `route_preference` to either
     * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
     * taking traffic conditions into account.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 5;</code>
     */
    public com.google.protobuf.Duration.Builder getDurationBuilder() {
      
      onChanged();
      return getDurationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The length of time needed to navigate the route. If you set the
     * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
     * `static_duration`. If you set the `route_preference` to either
     * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
     * taking traffic conditions into account.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 5;</code>
     */
    public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
      if (durationBuilder_ != null) {
        return durationBuilder_.getMessageOrBuilder();
      } else {
        return duration_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : duration_;
      }
    }
    /**
     * <pre>
     * The length of time needed to navigate the route. If you set the
     * `route_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
     * `static_duration`. If you set the `route_preference` to either
     * `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
     * taking traffic conditions into account.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getDurationFieldBuilder() {
      if (durationBuilder_ == null) {
        durationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getDuration(),
                getParentForChildren(),
                isClean());
        duration_ = null;
      }
      return durationBuilder_;
    }

    private com.google.protobuf.Duration staticDuration_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> staticDurationBuilder_;
    /**
     * <pre>
     * The duration of traveling through the route without taking traffic
     * conditions into consideration.
     * </pre>
     *
     * <code>.google.protobuf.Duration static_duration = 6;</code>
     * @return Whether the staticDuration field is set.
     */
    public boolean hasStaticDuration() {
      return staticDurationBuilder_ != null || staticDuration_ != null;
    }
    /**
     * <pre>
     * The duration of traveling through the route without taking traffic
     * conditions into consideration.
     * </pre>
     *
     * <code>.google.protobuf.Duration static_duration = 6;</code>
     * @return The staticDuration.
     */
    public com.google.protobuf.Duration getStaticDuration() {
      if (staticDurationBuilder_ == null) {
        return staticDuration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : staticDuration_;
      } else {
        return staticDurationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The duration of traveling through the route without taking traffic
     * conditions into consideration.
     * </pre>
     *
     * <code>.google.protobuf.Duration static_duration = 6;</code>
     */
    public Builder setStaticDuration(com.google.protobuf.Duration value) {
      if (staticDurationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        staticDuration_ = value;
        onChanged();
      } else {
        staticDurationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The duration of traveling through the route without taking traffic
     * conditions into consideration.
     * </pre>
     *
     * <code>.google.protobuf.Duration static_duration = 6;</code>
     */
    public Builder setStaticDuration(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (staticDurationBuilder_ == null) {
        staticDuration_ = builderForValue.build();
        onChanged();
      } else {
        staticDurationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The duration of traveling through the route without taking traffic
     * conditions into consideration.
     * </pre>
     *
     * <code>.google.protobuf.Duration static_duration = 6;</code>
     */
    public Builder mergeStaticDuration(com.google.protobuf.Duration value) {
      if (staticDurationBuilder_ == null) {
        if (staticDuration_ != null) {
          staticDuration_ =
            com.google.protobuf.Duration.newBuilder(staticDuration_).mergeFrom(value).buildPartial();
        } else {
          staticDuration_ = value;
        }
        onChanged();
      } else {
        staticDurationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The duration of traveling through the route without taking traffic
     * conditions into consideration.
     * </pre>
     *
     * <code>.google.protobuf.Duration static_duration = 6;</code>
     */
    public Builder clearStaticDuration() {
      if (staticDurationBuilder_ == null) {
        staticDuration_ = null;
        onChanged();
      } else {
        staticDuration_ = null;
        staticDurationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The duration of traveling through the route without taking traffic
     * conditions into consideration.
     * </pre>
     *
     * <code>.google.protobuf.Duration static_duration = 6;</code>
     */
    public com.google.protobuf.Duration.Builder getStaticDurationBuilder() {
      
      onChanged();
      return getStaticDurationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The duration of traveling through the route without taking traffic
     * conditions into consideration.
     * </pre>
     *
     * <code>.google.protobuf.Duration static_duration = 6;</code>
     */
    public com.google.protobuf.DurationOrBuilder getStaticDurationOrBuilder() {
      if (staticDurationBuilder_ != null) {
        return staticDurationBuilder_.getMessageOrBuilder();
      } else {
        return staticDuration_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : staticDuration_;
      }
    }
    /**
     * <pre>
     * The duration of traveling through the route without taking traffic
     * conditions into consideration.
     * </pre>
     *
     * <code>.google.protobuf.Duration static_duration = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getStaticDurationFieldBuilder() {
      if (staticDurationBuilder_ == null) {
        staticDurationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getStaticDuration(),
                getParentForChildren(),
                isClean());
        staticDuration_ = null;
      }
      return staticDurationBuilder_;
    }

    private com.google.maps.routes.v1.RouteTravelAdvisory travelAdvisory_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.maps.routes.v1.RouteTravelAdvisory, com.google.maps.routes.v1.RouteTravelAdvisory.Builder, com.google.maps.routes.v1.RouteTravelAdvisoryOrBuilder> travelAdvisoryBuilder_;
    /**
     * <pre>
     * Additional information about the route. For example: restriction
     * information and toll information
     * </pre>
     *
     * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
     * @return Whether the travelAdvisory field is set.
     */
    public boolean hasTravelAdvisory() {
      return travelAdvisoryBuilder_ != null || travelAdvisory_ != null;
    }
    /**
     * <pre>
     * Additional information about the route. For example: restriction
     * information and toll information
     * </pre>
     *
     * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
     * @return The travelAdvisory.
     */
    public com.google.maps.routes.v1.RouteTravelAdvisory getTravelAdvisory() {
      if (travelAdvisoryBuilder_ == null) {
        return travelAdvisory_ == null ? com.google.maps.routes.v1.RouteTravelAdvisory.getDefaultInstance() : travelAdvisory_;
      } else {
        return travelAdvisoryBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Additional information about the route. For example: restriction
     * information and toll information
     * </pre>
     *
     * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
     */
    public Builder setTravelAdvisory(com.google.maps.routes.v1.RouteTravelAdvisory value) {
      if (travelAdvisoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        travelAdvisory_ = value;
        onChanged();
      } else {
        travelAdvisoryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Additional information about the route. For example: restriction
     * information and toll information
     * </pre>
     *
     * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
     */
    public Builder setTravelAdvisory(
        com.google.maps.routes.v1.RouteTravelAdvisory.Builder builderForValue) {
      if (travelAdvisoryBuilder_ == null) {
        travelAdvisory_ = builderForValue.build();
        onChanged();
      } else {
        travelAdvisoryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Additional information about the route. For example: restriction
     * information and toll information
     * </pre>
     *
     * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
     */
    public Builder mergeTravelAdvisory(com.google.maps.routes.v1.RouteTravelAdvisory value) {
      if (travelAdvisoryBuilder_ == null) {
        if (travelAdvisory_ != null) {
          travelAdvisory_ =
            com.google.maps.routes.v1.RouteTravelAdvisory.newBuilder(travelAdvisory_).mergeFrom(value).buildPartial();
        } else {
          travelAdvisory_ = value;
        }
        onChanged();
      } else {
        travelAdvisoryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Additional information about the route. For example: restriction
     * information and toll information
     * </pre>
     *
     * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
     */
    public Builder clearTravelAdvisory() {
      if (travelAdvisoryBuilder_ == null) {
        travelAdvisory_ = null;
        onChanged();
      } else {
        travelAdvisory_ = null;
        travelAdvisoryBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Additional information about the route. For example: restriction
     * information and toll information
     * </pre>
     *
     * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
     */
    public com.google.maps.routes.v1.RouteTravelAdvisory.Builder getTravelAdvisoryBuilder() {
      
      onChanged();
      return getTravelAdvisoryFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Additional information about the route. For example: restriction
     * information and toll information
     * </pre>
     *
     * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
     */
    public com.google.maps.routes.v1.RouteTravelAdvisoryOrBuilder getTravelAdvisoryOrBuilder() {
      if (travelAdvisoryBuilder_ != null) {
        return travelAdvisoryBuilder_.getMessageOrBuilder();
      } else {
        return travelAdvisory_ == null ?
            com.google.maps.routes.v1.RouteTravelAdvisory.getDefaultInstance() : travelAdvisory_;
      }
    }
    /**
     * <pre>
     * Additional information about the route. For example: restriction
     * information and toll information
     * </pre>
     *
     * <code>.google.maps.routes.v1.RouteTravelAdvisory travel_advisory = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.maps.routes.v1.RouteTravelAdvisory, com.google.maps.routes.v1.RouteTravelAdvisory.Builder, com.google.maps.routes.v1.RouteTravelAdvisoryOrBuilder> 
        getTravelAdvisoryFieldBuilder() {
      if (travelAdvisoryBuilder_ == null) {
        travelAdvisoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.maps.routes.v1.RouteTravelAdvisory, com.google.maps.routes.v1.RouteTravelAdvisory.Builder, com.google.maps.routes.v1.RouteTravelAdvisoryOrBuilder>(
                getTravelAdvisory(),
                getParentForChildren(),
                isClean());
        travelAdvisory_ = null;
      }
      return travelAdvisoryBuilder_;
    }

    private com.google.maps.routes.v1.FallbackInfo fallbackInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.maps.routes.v1.FallbackInfo, com.google.maps.routes.v1.FallbackInfo.Builder, com.google.maps.routes.v1.FallbackInfoOrBuilder> fallbackInfoBuilder_;
    /**
     * <pre>
     * In some cases when the server is not able to compute the route with the
     * given preferences for this particular origin/destination pair, it may
     * fall back to using a different mode of computation. When fallback mode is
     * used, this field contains detailed information about the fallback response.
     * Otherwise this field is unset.
     * </pre>
     *
     * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
     * @return Whether the fallbackInfo field is set.
     */
    public boolean hasFallbackInfo() {
      return fallbackInfoBuilder_ != null || fallbackInfo_ != null;
    }
    /**
     * <pre>
     * In some cases when the server is not able to compute the route with the
     * given preferences for this particular origin/destination pair, it may
     * fall back to using a different mode of computation. When fallback mode is
     * used, this field contains detailed information about the fallback response.
     * Otherwise this field is unset.
     * </pre>
     *
     * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
     * @return The fallbackInfo.
     */
    public com.google.maps.routes.v1.FallbackInfo getFallbackInfo() {
      if (fallbackInfoBuilder_ == null) {
        return fallbackInfo_ == null ? com.google.maps.routes.v1.FallbackInfo.getDefaultInstance() : fallbackInfo_;
      } else {
        return fallbackInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * In some cases when the server is not able to compute the route with the
     * given preferences for this particular origin/destination pair, it may
     * fall back to using a different mode of computation. When fallback mode is
     * used, this field contains detailed information about the fallback response.
     * Otherwise this field is unset.
     * </pre>
     *
     * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
     */
    public Builder setFallbackInfo(com.google.maps.routes.v1.FallbackInfo value) {
      if (fallbackInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fallbackInfo_ = value;
        onChanged();
      } else {
        fallbackInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * In some cases when the server is not able to compute the route with the
     * given preferences for this particular origin/destination pair, it may
     * fall back to using a different mode of computation. When fallback mode is
     * used, this field contains detailed information about the fallback response.
     * Otherwise this field is unset.
     * </pre>
     *
     * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
     */
    public Builder setFallbackInfo(
        com.google.maps.routes.v1.FallbackInfo.Builder builderForValue) {
      if (fallbackInfoBuilder_ == null) {
        fallbackInfo_ = builderForValue.build();
        onChanged();
      } else {
        fallbackInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * In some cases when the server is not able to compute the route with the
     * given preferences for this particular origin/destination pair, it may
     * fall back to using a different mode of computation. When fallback mode is
     * used, this field contains detailed information about the fallback response.
     * Otherwise this field is unset.
     * </pre>
     *
     * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
     */
    public Builder mergeFallbackInfo(com.google.maps.routes.v1.FallbackInfo value) {
      if (fallbackInfoBuilder_ == null) {
        if (fallbackInfo_ != null) {
          fallbackInfo_ =
            com.google.maps.routes.v1.FallbackInfo.newBuilder(fallbackInfo_).mergeFrom(value).buildPartial();
        } else {
          fallbackInfo_ = value;
        }
        onChanged();
      } else {
        fallbackInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * In some cases when the server is not able to compute the route with the
     * given preferences for this particular origin/destination pair, it may
     * fall back to using a different mode of computation. When fallback mode is
     * used, this field contains detailed information about the fallback response.
     * Otherwise this field is unset.
     * </pre>
     *
     * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
     */
    public Builder clearFallbackInfo() {
      if (fallbackInfoBuilder_ == null) {
        fallbackInfo_ = null;
        onChanged();
      } else {
        fallbackInfo_ = null;
        fallbackInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * In some cases when the server is not able to compute the route with the
     * given preferences for this particular origin/destination pair, it may
     * fall back to using a different mode of computation. When fallback mode is
     * used, this field contains detailed information about the fallback response.
     * Otherwise this field is unset.
     * </pre>
     *
     * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
     */
    public com.google.maps.routes.v1.FallbackInfo.Builder getFallbackInfoBuilder() {
      
      onChanged();
      return getFallbackInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * In some cases when the server is not able to compute the route with the
     * given preferences for this particular origin/destination pair, it may
     * fall back to using a different mode of computation. When fallback mode is
     * used, this field contains detailed information about the fallback response.
     * Otherwise this field is unset.
     * </pre>
     *
     * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
     */
    public com.google.maps.routes.v1.FallbackInfoOrBuilder getFallbackInfoOrBuilder() {
      if (fallbackInfoBuilder_ != null) {
        return fallbackInfoBuilder_.getMessageOrBuilder();
      } else {
        return fallbackInfo_ == null ?
            com.google.maps.routes.v1.FallbackInfo.getDefaultInstance() : fallbackInfo_;
      }
    }
    /**
     * <pre>
     * In some cases when the server is not able to compute the route with the
     * given preferences for this particular origin/destination pair, it may
     * fall back to using a different mode of computation. When fallback mode is
     * used, this field contains detailed information about the fallback response.
     * Otherwise this field is unset.
     * </pre>
     *
     * <code>.google.maps.routes.v1.FallbackInfo fallback_info = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.maps.routes.v1.FallbackInfo, com.google.maps.routes.v1.FallbackInfo.Builder, com.google.maps.routes.v1.FallbackInfoOrBuilder> 
        getFallbackInfoFieldBuilder() {
      if (fallbackInfoBuilder_ == null) {
        fallbackInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.maps.routes.v1.FallbackInfo, com.google.maps.routes.v1.FallbackInfo.Builder, com.google.maps.routes.v1.FallbackInfoOrBuilder>(
                getFallbackInfo(),
                getParentForChildren(),
                isClean());
        fallbackInfo_ = null;
      }
      return fallbackInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.maps.routes.v1.RouteMatrixElement)
  }

  // @@protoc_insertion_point(class_scope:google.maps.routes.v1.RouteMatrixElement)
  private static final com.google.maps.routes.v1.RouteMatrixElement DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.maps.routes.v1.RouteMatrixElement();
  }

  public static com.google.maps.routes.v1.RouteMatrixElement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RouteMatrixElement>
      PARSER = new com.google.protobuf.AbstractParser<RouteMatrixElement>() {
    @java.lang.Override
    public RouteMatrixElement parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RouteMatrixElement(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RouteMatrixElement> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RouteMatrixElement> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.maps.routes.v1.RouteMatrixElement getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

