// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/route.proto

package com.google.maps.routes.v1;

public interface RouteLegTravelAdvisoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.maps.routes.v1.RouteLegTravelAdvisory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Encapsulates information about tolls on the specific RouteLeg.
   * This field is only populated if we expect there are tolls on the RouteLeg.
   * If this field is set but the estimated_price subfield is not populated,
   * we expect that road contains tolls but we do not know an estimated price.
   * If this field does not exist, then there is no toll on the RouteLeg.
   * </pre>
   *
   * <code>.google.maps.routes.v1.TollInfo toll_info = 1;</code>
   * @return Whether the tollInfo field is set.
   */
  boolean hasTollInfo();
  /**
   * <pre>
   * Encapsulates information about tolls on the specific RouteLeg.
   * This field is only populated if we expect there are tolls on the RouteLeg.
   * If this field is set but the estimated_price subfield is not populated,
   * we expect that road contains tolls but we do not know an estimated price.
   * If this field does not exist, then there is no toll on the RouteLeg.
   * </pre>
   *
   * <code>.google.maps.routes.v1.TollInfo toll_info = 1;</code>
   * @return The tollInfo.
   */
  com.google.maps.routes.v1.TollInfo getTollInfo();
  /**
   * <pre>
   * Encapsulates information about tolls on the specific RouteLeg.
   * This field is only populated if we expect there are tolls on the RouteLeg.
   * If this field is set but the estimated_price subfield is not populated,
   * we expect that road contains tolls but we do not know an estimated price.
   * If this field does not exist, then there is no toll on the RouteLeg.
   * </pre>
   *
   * <code>.google.maps.routes.v1.TollInfo toll_info = 1;</code>
   */
  com.google.maps.routes.v1.TollInfoOrBuilder getTollInfoOrBuilder();
}
