// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/route.proto

package com.google.maps.routes.v1;

public interface RouteLegTravelAdvisoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.maps.routes.v1.RouteLegTravelAdvisory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Populated if the corresponding RouteLeg of the journey contains toll roads.
   * TollInfo encapsulates the estimated amount of toll collected on this leg,
   * grouped by relevant currencies.
   * </pre>
   *
   * <code>.google.maps.routes.v1.TollInfo toll_info = 1;</code>
   * @return Whether the tollInfo field is set.
   */
  boolean hasTollInfo();
  /**
   * <pre>
   * Populated if the corresponding RouteLeg of the journey contains toll roads.
   * TollInfo encapsulates the estimated amount of toll collected on this leg,
   * grouped by relevant currencies.
   * </pre>
   *
   * <code>.google.maps.routes.v1.TollInfo toll_info = 1;</code>
   * @return The tollInfo.
   */
  com.google.maps.routes.v1.TollInfo getTollInfo();
  /**
   * <pre>
   * Populated if the corresponding RouteLeg of the journey contains toll roads.
   * TollInfo encapsulates the estimated amount of toll collected on this leg,
   * grouped by relevant currencies.
   * </pre>
   *
   * <code>.google.maps.routes.v1.TollInfo toll_info = 1;</code>
   */
  com.google.maps.routes.v1.TollInfoOrBuilder getTollInfoOrBuilder();
}
