// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/toll_passes.proto

package com.google.maps.routes.v1;

/**
 * <pre>
 * List of toll passes around the world that we support.
 * </pre>
 *
 * Protobuf enum {@code google.maps.routes.v1.TollPass}
 */
public enum TollPass
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Not used. If this value is used, then the request fails.
   * </pre>
   *
   * <code>TOLL_PASS_UNSPECIFIED = 0;</code>
   */
  TOLL_PASS_UNSPECIFIED(0),
  /**
   * <pre>
   * State pass of the Washington state, United States.
   * </pre>
   *
   * <code>US_WA_GOOD_TO_GO = 1;</code>
   */
  US_WA_GOOD_TO_GO(1),
  /**
   * <pre>
   * E-tag pass in Australia.
   * </pre>
   *
   * <code>AU_E_TAG = 2;</code>
   */
  AU_E_TAG(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Not used. If this value is used, then the request fails.
   * </pre>
   *
   * <code>TOLL_PASS_UNSPECIFIED = 0;</code>
   */
  public static final int TOLL_PASS_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * State pass of the Washington state, United States.
   * </pre>
   *
   * <code>US_WA_GOOD_TO_GO = 1;</code>
   */
  public static final int US_WA_GOOD_TO_GO_VALUE = 1;
  /**
   * <pre>
   * E-tag pass in Australia.
   * </pre>
   *
   * <code>AU_E_TAG = 2;</code>
   */
  public static final int AU_E_TAG_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TollPass valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TollPass forNumber(int value) {
    switch (value) {
      case 0: return TOLL_PASS_UNSPECIFIED;
      case 1: return US_WA_GOOD_TO_GO;
      case 2: return AU_E_TAG;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TollPass>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TollPass> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TollPass>() {
          public TollPass findValueByNumber(int number) {
            return TollPass.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.maps.routes.v1.TollPassesProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final TollPass[] VALUES = values();

  public static TollPass valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TollPass(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.maps.routes.v1.TollPass)
}

