// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/route.proto

package com.google.maps.routes.v1;

/**
 * <pre>
 * Encapsulates the traffic restriction applied to the route. As of October
 * 2019, only Jakarta, Indonesia takes into consideration.
 * </pre>
 *
 * Protobuf type {@code google.maps.routes.v1.TrafficRestriction}
 */
public  final class TrafficRestriction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.maps.routes.v1.TrafficRestriction)
    TrafficRestrictionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrafficRestriction.newBuilder() to construct.
  private TrafficRestriction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrafficRestriction() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrafficRestriction();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrafficRestriction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.Builder subBuilder = null;
            if (licensePlateLastCharacterRestriction_ != null) {
              subBuilder = licensePlateLastCharacterRestriction_.toBuilder();
            }
            licensePlateLastCharacterRestriction_ = input.readMessage(com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(licensePlateLastCharacterRestriction_);
              licensePlateLastCharacterRestriction_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_TrafficRestriction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_TrafficRestriction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.maps.routes.v1.TrafficRestriction.class, com.google.maps.routes.v1.TrafficRestriction.Builder.class);
  }

  public static final int LICENSE_PLATE_LAST_CHARACTER_RESTRICTION_FIELD_NUMBER = 1;
  private com.google.maps.routes.v1.LicensePlateLastCharacterRestriction licensePlateLastCharacterRestriction_;
  /**
   * <pre>
   * The restriction based on the vehicle's license plate last character. If
   * this field does not exist, then no restriction on route.
   * </pre>
   *
   * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
   * @return Whether the licensePlateLastCharacterRestriction field is set.
   */
  public boolean hasLicensePlateLastCharacterRestriction() {
    return licensePlateLastCharacterRestriction_ != null;
  }
  /**
   * <pre>
   * The restriction based on the vehicle's license plate last character. If
   * this field does not exist, then no restriction on route.
   * </pre>
   *
   * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
   * @return The licensePlateLastCharacterRestriction.
   */
  public com.google.maps.routes.v1.LicensePlateLastCharacterRestriction getLicensePlateLastCharacterRestriction() {
    return licensePlateLastCharacterRestriction_ == null ? com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.getDefaultInstance() : licensePlateLastCharacterRestriction_;
  }
  /**
   * <pre>
   * The restriction based on the vehicle's license plate last character. If
   * this field does not exist, then no restriction on route.
   * </pre>
   *
   * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
   */
  public com.google.maps.routes.v1.LicensePlateLastCharacterRestrictionOrBuilder getLicensePlateLastCharacterRestrictionOrBuilder() {
    return getLicensePlateLastCharacterRestriction();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (licensePlateLastCharacterRestriction_ != null) {
      output.writeMessage(1, getLicensePlateLastCharacterRestriction());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (licensePlateLastCharacterRestriction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLicensePlateLastCharacterRestriction());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.maps.routes.v1.TrafficRestriction)) {
      return super.equals(obj);
    }
    com.google.maps.routes.v1.TrafficRestriction other = (com.google.maps.routes.v1.TrafficRestriction) obj;

    if (hasLicensePlateLastCharacterRestriction() != other.hasLicensePlateLastCharacterRestriction()) return false;
    if (hasLicensePlateLastCharacterRestriction()) {
      if (!getLicensePlateLastCharacterRestriction()
          .equals(other.getLicensePlateLastCharacterRestriction())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLicensePlateLastCharacterRestriction()) {
      hash = (37 * hash) + LICENSE_PLATE_LAST_CHARACTER_RESTRICTION_FIELD_NUMBER;
      hash = (53 * hash) + getLicensePlateLastCharacterRestriction().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.TrafficRestriction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.maps.routes.v1.TrafficRestriction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Encapsulates the traffic restriction applied to the route. As of October
   * 2019, only Jakarta, Indonesia takes into consideration.
   * </pre>
   *
   * Protobuf type {@code google.maps.routes.v1.TrafficRestriction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.maps.routes.v1.TrafficRestriction)
      com.google.maps.routes.v1.TrafficRestrictionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_TrafficRestriction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_TrafficRestriction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.maps.routes.v1.TrafficRestriction.class, com.google.maps.routes.v1.TrafficRestriction.Builder.class);
    }

    // Construct using com.google.maps.routes.v1.TrafficRestriction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (licensePlateLastCharacterRestrictionBuilder_ == null) {
        licensePlateLastCharacterRestriction_ = null;
      } else {
        licensePlateLastCharacterRestriction_ = null;
        licensePlateLastCharacterRestrictionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.maps.routes.v1.RouteProto.internal_static_google_maps_routes_v1_TrafficRestriction_descriptor;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.TrafficRestriction getDefaultInstanceForType() {
      return com.google.maps.routes.v1.TrafficRestriction.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.maps.routes.v1.TrafficRestriction build() {
      com.google.maps.routes.v1.TrafficRestriction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.TrafficRestriction buildPartial() {
      com.google.maps.routes.v1.TrafficRestriction result = new com.google.maps.routes.v1.TrafficRestriction(this);
      if (licensePlateLastCharacterRestrictionBuilder_ == null) {
        result.licensePlateLastCharacterRestriction_ = licensePlateLastCharacterRestriction_;
      } else {
        result.licensePlateLastCharacterRestriction_ = licensePlateLastCharacterRestrictionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.maps.routes.v1.TrafficRestriction) {
        return mergeFrom((com.google.maps.routes.v1.TrafficRestriction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.maps.routes.v1.TrafficRestriction other) {
      if (other == com.google.maps.routes.v1.TrafficRestriction.getDefaultInstance()) return this;
      if (other.hasLicensePlateLastCharacterRestriction()) {
        mergeLicensePlateLastCharacterRestriction(other.getLicensePlateLastCharacterRestriction());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.maps.routes.v1.TrafficRestriction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.maps.routes.v1.TrafficRestriction) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.maps.routes.v1.LicensePlateLastCharacterRestriction licensePlateLastCharacterRestriction_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.maps.routes.v1.LicensePlateLastCharacterRestriction, com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.Builder, com.google.maps.routes.v1.LicensePlateLastCharacterRestrictionOrBuilder> licensePlateLastCharacterRestrictionBuilder_;
    /**
     * <pre>
     * The restriction based on the vehicle's license plate last character. If
     * this field does not exist, then no restriction on route.
     * </pre>
     *
     * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
     * @return Whether the licensePlateLastCharacterRestriction field is set.
     */
    public boolean hasLicensePlateLastCharacterRestriction() {
      return licensePlateLastCharacterRestrictionBuilder_ != null || licensePlateLastCharacterRestriction_ != null;
    }
    /**
     * <pre>
     * The restriction based on the vehicle's license plate last character. If
     * this field does not exist, then no restriction on route.
     * </pre>
     *
     * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
     * @return The licensePlateLastCharacterRestriction.
     */
    public com.google.maps.routes.v1.LicensePlateLastCharacterRestriction getLicensePlateLastCharacterRestriction() {
      if (licensePlateLastCharacterRestrictionBuilder_ == null) {
        return licensePlateLastCharacterRestriction_ == null ? com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.getDefaultInstance() : licensePlateLastCharacterRestriction_;
      } else {
        return licensePlateLastCharacterRestrictionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The restriction based on the vehicle's license plate last character. If
     * this field does not exist, then no restriction on route.
     * </pre>
     *
     * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
     */
    public Builder setLicensePlateLastCharacterRestriction(com.google.maps.routes.v1.LicensePlateLastCharacterRestriction value) {
      if (licensePlateLastCharacterRestrictionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        licensePlateLastCharacterRestriction_ = value;
        onChanged();
      } else {
        licensePlateLastCharacterRestrictionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The restriction based on the vehicle's license plate last character. If
     * this field does not exist, then no restriction on route.
     * </pre>
     *
     * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
     */
    public Builder setLicensePlateLastCharacterRestriction(
        com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.Builder builderForValue) {
      if (licensePlateLastCharacterRestrictionBuilder_ == null) {
        licensePlateLastCharacterRestriction_ = builderForValue.build();
        onChanged();
      } else {
        licensePlateLastCharacterRestrictionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The restriction based on the vehicle's license plate last character. If
     * this field does not exist, then no restriction on route.
     * </pre>
     *
     * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
     */
    public Builder mergeLicensePlateLastCharacterRestriction(com.google.maps.routes.v1.LicensePlateLastCharacterRestriction value) {
      if (licensePlateLastCharacterRestrictionBuilder_ == null) {
        if (licensePlateLastCharacterRestriction_ != null) {
          licensePlateLastCharacterRestriction_ =
            com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.newBuilder(licensePlateLastCharacterRestriction_).mergeFrom(value).buildPartial();
        } else {
          licensePlateLastCharacterRestriction_ = value;
        }
        onChanged();
      } else {
        licensePlateLastCharacterRestrictionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The restriction based on the vehicle's license plate last character. If
     * this field does not exist, then no restriction on route.
     * </pre>
     *
     * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
     */
    public Builder clearLicensePlateLastCharacterRestriction() {
      if (licensePlateLastCharacterRestrictionBuilder_ == null) {
        licensePlateLastCharacterRestriction_ = null;
        onChanged();
      } else {
        licensePlateLastCharacterRestriction_ = null;
        licensePlateLastCharacterRestrictionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The restriction based on the vehicle's license plate last character. If
     * this field does not exist, then no restriction on route.
     * </pre>
     *
     * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
     */
    public com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.Builder getLicensePlateLastCharacterRestrictionBuilder() {
      
      onChanged();
      return getLicensePlateLastCharacterRestrictionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The restriction based on the vehicle's license plate last character. If
     * this field does not exist, then no restriction on route.
     * </pre>
     *
     * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
     */
    public com.google.maps.routes.v1.LicensePlateLastCharacterRestrictionOrBuilder getLicensePlateLastCharacterRestrictionOrBuilder() {
      if (licensePlateLastCharacterRestrictionBuilder_ != null) {
        return licensePlateLastCharacterRestrictionBuilder_.getMessageOrBuilder();
      } else {
        return licensePlateLastCharacterRestriction_ == null ?
            com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.getDefaultInstance() : licensePlateLastCharacterRestriction_;
      }
    }
    /**
     * <pre>
     * The restriction based on the vehicle's license plate last character. If
     * this field does not exist, then no restriction on route.
     * </pre>
     *
     * <code>.google.maps.routes.v1.LicensePlateLastCharacterRestriction license_plate_last_character_restriction = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.maps.routes.v1.LicensePlateLastCharacterRestriction, com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.Builder, com.google.maps.routes.v1.LicensePlateLastCharacterRestrictionOrBuilder> 
        getLicensePlateLastCharacterRestrictionFieldBuilder() {
      if (licensePlateLastCharacterRestrictionBuilder_ == null) {
        licensePlateLastCharacterRestrictionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.maps.routes.v1.LicensePlateLastCharacterRestriction, com.google.maps.routes.v1.LicensePlateLastCharacterRestriction.Builder, com.google.maps.routes.v1.LicensePlateLastCharacterRestrictionOrBuilder>(
                getLicensePlateLastCharacterRestriction(),
                getParentForChildren(),
                isClean());
        licensePlateLastCharacterRestriction_ = null;
      }
      return licensePlateLastCharacterRestrictionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.maps.routes.v1.TrafficRestriction)
  }

  // @@protoc_insertion_point(class_scope:google.maps.routes.v1.TrafficRestriction)
  private static final com.google.maps.routes.v1.TrafficRestriction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.maps.routes.v1.TrafficRestriction();
  }

  public static com.google.maps.routes.v1.TrafficRestriction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrafficRestriction>
      PARSER = new com.google.protobuf.AbstractParser<TrafficRestriction>() {
    @java.lang.Override
    public TrafficRestriction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrafficRestriction(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrafficRestriction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrafficRestriction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.maps.routes.v1.TrafficRestriction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

