// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/compute_routes_request.proto

package com.google.maps.routes.v1;

public interface VehicleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.maps.routes.v1.VehicleInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Specifies the license plate last character. Could be a digit or a letter.
   * </pre>
   *
   * <code>string license_plate_last_character = 1;</code>
   * @return The licensePlateLastCharacter.
   */
  java.lang.String getLicensePlateLastCharacter();
  /**
   * <pre>
   * Specifies the license plate last character. Could be a digit or a letter.
   * </pre>
   *
   * <code>string license_plate_last_character = 1;</code>
   * @return The bytes for licensePlateLastCharacter.
   */
  com.google.protobuf.ByteString
      getLicensePlateLastCharacterBytes();

  /**
   * <pre>
   * Describes the vehicle's emission type.
   * Applies only to the DRIVE travel mode.
   * </pre>
   *
   * <code>.google.maps.routes.v1.VehicleEmissionType emission_type = 2;</code>
   * @return The enum numeric value on the wire for emissionType.
   */
  int getEmissionTypeValue();
  /**
   * <pre>
   * Describes the vehicle's emission type.
   * Applies only to the DRIVE travel mode.
   * </pre>
   *
   * <code>.google.maps.routes.v1.VehicleEmissionType emission_type = 2;</code>
   * @return The emissionType.
   */
  com.google.maps.routes.v1.VehicleEmissionType getEmissionType();
}
