// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/routes/v1/compute_routes_request.proto

package com.google.maps.routes.v1;

/**
 * <pre>
 * Encapsulates the vehicle information, such as the license plate last
 * character.
 * </pre>
 *
 * Protobuf type {@code google.maps.routes.v1.VehicleInfo}
 */
public  final class VehicleInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.maps.routes.v1.VehicleInfo)
    VehicleInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VehicleInfo.newBuilder() to construct.
  private VehicleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VehicleInfo() {
    licensePlateLastCharacter_ = "";
    emissionType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VehicleInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VehicleInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            licensePlateLastCharacter_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            emissionType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.maps.routes.v1.ComputeRoutesRequestProto.internal_static_google_maps_routes_v1_VehicleInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.maps.routes.v1.ComputeRoutesRequestProto.internal_static_google_maps_routes_v1_VehicleInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.maps.routes.v1.VehicleInfo.class, com.google.maps.routes.v1.VehicleInfo.Builder.class);
  }

  public static final int LICENSE_PLATE_LAST_CHARACTER_FIELD_NUMBER = 1;
  private volatile java.lang.Object licensePlateLastCharacter_;
  /**
   * <pre>
   * Specifies the license plate last character. Could be a digit or a letter.
   * </pre>
   *
   * <code>string license_plate_last_character = 1;</code>
   * @return The licensePlateLastCharacter.
   */
  public java.lang.String getLicensePlateLastCharacter() {
    java.lang.Object ref = licensePlateLastCharacter_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      licensePlateLastCharacter_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Specifies the license plate last character. Could be a digit or a letter.
   * </pre>
   *
   * <code>string license_plate_last_character = 1;</code>
   * @return The bytes for licensePlateLastCharacter.
   */
  public com.google.protobuf.ByteString
      getLicensePlateLastCharacterBytes() {
    java.lang.Object ref = licensePlateLastCharacter_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      licensePlateLastCharacter_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMISSION_TYPE_FIELD_NUMBER = 2;
  private int emissionType_;
  /**
   * <pre>
   * Describes the vehicle's emission type.
   * Applies only to the DRIVE travel mode.
   * </pre>
   *
   * <code>.google.maps.routes.v1.VehicleEmissionType emission_type = 2;</code>
   * @return The enum numeric value on the wire for emissionType.
   */
  public int getEmissionTypeValue() {
    return emissionType_;
  }
  /**
   * <pre>
   * Describes the vehicle's emission type.
   * Applies only to the DRIVE travel mode.
   * </pre>
   *
   * <code>.google.maps.routes.v1.VehicleEmissionType emission_type = 2;</code>
   * @return The emissionType.
   */
  public com.google.maps.routes.v1.VehicleEmissionType getEmissionType() {
    @SuppressWarnings("deprecation")
    com.google.maps.routes.v1.VehicleEmissionType result = com.google.maps.routes.v1.VehicleEmissionType.valueOf(emissionType_);
    return result == null ? com.google.maps.routes.v1.VehicleEmissionType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getLicensePlateLastCharacterBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, licensePlateLastCharacter_);
    }
    if (emissionType_ != com.google.maps.routes.v1.VehicleEmissionType.VEHICLE_EMISSION_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, emissionType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getLicensePlateLastCharacterBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, licensePlateLastCharacter_);
    }
    if (emissionType_ != com.google.maps.routes.v1.VehicleEmissionType.VEHICLE_EMISSION_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, emissionType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.maps.routes.v1.VehicleInfo)) {
      return super.equals(obj);
    }
    com.google.maps.routes.v1.VehicleInfo other = (com.google.maps.routes.v1.VehicleInfo) obj;

    if (!getLicensePlateLastCharacter()
        .equals(other.getLicensePlateLastCharacter())) return false;
    if (emissionType_ != other.emissionType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LICENSE_PLATE_LAST_CHARACTER_FIELD_NUMBER;
    hash = (53 * hash) + getLicensePlateLastCharacter().hashCode();
    hash = (37 * hash) + EMISSION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + emissionType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.maps.routes.v1.VehicleInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.maps.routes.v1.VehicleInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.maps.routes.v1.VehicleInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Encapsulates the vehicle information, such as the license plate last
   * character.
   * </pre>
   *
   * Protobuf type {@code google.maps.routes.v1.VehicleInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.maps.routes.v1.VehicleInfo)
      com.google.maps.routes.v1.VehicleInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.maps.routes.v1.ComputeRoutesRequestProto.internal_static_google_maps_routes_v1_VehicleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.maps.routes.v1.ComputeRoutesRequestProto.internal_static_google_maps_routes_v1_VehicleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.maps.routes.v1.VehicleInfo.class, com.google.maps.routes.v1.VehicleInfo.Builder.class);
    }

    // Construct using com.google.maps.routes.v1.VehicleInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      licensePlateLastCharacter_ = "";

      emissionType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.maps.routes.v1.ComputeRoutesRequestProto.internal_static_google_maps_routes_v1_VehicleInfo_descriptor;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.VehicleInfo getDefaultInstanceForType() {
      return com.google.maps.routes.v1.VehicleInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.maps.routes.v1.VehicleInfo build() {
      com.google.maps.routes.v1.VehicleInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.maps.routes.v1.VehicleInfo buildPartial() {
      com.google.maps.routes.v1.VehicleInfo result = new com.google.maps.routes.v1.VehicleInfo(this);
      result.licensePlateLastCharacter_ = licensePlateLastCharacter_;
      result.emissionType_ = emissionType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.maps.routes.v1.VehicleInfo) {
        return mergeFrom((com.google.maps.routes.v1.VehicleInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.maps.routes.v1.VehicleInfo other) {
      if (other == com.google.maps.routes.v1.VehicleInfo.getDefaultInstance()) return this;
      if (!other.getLicensePlateLastCharacter().isEmpty()) {
        licensePlateLastCharacter_ = other.licensePlateLastCharacter_;
        onChanged();
      }
      if (other.emissionType_ != 0) {
        setEmissionTypeValue(other.getEmissionTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.maps.routes.v1.VehicleInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.maps.routes.v1.VehicleInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object licensePlateLastCharacter_ = "";
    /**
     * <pre>
     * Specifies the license plate last character. Could be a digit or a letter.
     * </pre>
     *
     * <code>string license_plate_last_character = 1;</code>
     * @return The licensePlateLastCharacter.
     */
    public java.lang.String getLicensePlateLastCharacter() {
      java.lang.Object ref = licensePlateLastCharacter_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        licensePlateLastCharacter_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Specifies the license plate last character. Could be a digit or a letter.
     * </pre>
     *
     * <code>string license_plate_last_character = 1;</code>
     * @return The bytes for licensePlateLastCharacter.
     */
    public com.google.protobuf.ByteString
        getLicensePlateLastCharacterBytes() {
      java.lang.Object ref = licensePlateLastCharacter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        licensePlateLastCharacter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Specifies the license plate last character. Could be a digit or a letter.
     * </pre>
     *
     * <code>string license_plate_last_character = 1;</code>
     * @param value The licensePlateLastCharacter to set.
     * @return This builder for chaining.
     */
    public Builder setLicensePlateLastCharacter(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      licensePlateLastCharacter_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Specifies the license plate last character. Could be a digit or a letter.
     * </pre>
     *
     * <code>string license_plate_last_character = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLicensePlateLastCharacter() {
      
      licensePlateLastCharacter_ = getDefaultInstance().getLicensePlateLastCharacter();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Specifies the license plate last character. Could be a digit or a letter.
     * </pre>
     *
     * <code>string license_plate_last_character = 1;</code>
     * @param value The bytes for licensePlateLastCharacter to set.
     * @return This builder for chaining.
     */
    public Builder setLicensePlateLastCharacterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      licensePlateLastCharacter_ = value;
      onChanged();
      return this;
    }

    private int emissionType_ = 0;
    /**
     * <pre>
     * Describes the vehicle's emission type.
     * Applies only to the DRIVE travel mode.
     * </pre>
     *
     * <code>.google.maps.routes.v1.VehicleEmissionType emission_type = 2;</code>
     * @return The enum numeric value on the wire for emissionType.
     */
    public int getEmissionTypeValue() {
      return emissionType_;
    }
    /**
     * <pre>
     * Describes the vehicle's emission type.
     * Applies only to the DRIVE travel mode.
     * </pre>
     *
     * <code>.google.maps.routes.v1.VehicleEmissionType emission_type = 2;</code>
     * @param value The enum numeric value on the wire for emissionType to set.
     * @return This builder for chaining.
     */
    public Builder setEmissionTypeValue(int value) {
      emissionType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Describes the vehicle's emission type.
     * Applies only to the DRIVE travel mode.
     * </pre>
     *
     * <code>.google.maps.routes.v1.VehicleEmissionType emission_type = 2;</code>
     * @return The emissionType.
     */
    public com.google.maps.routes.v1.VehicleEmissionType getEmissionType() {
      @SuppressWarnings("deprecation")
      com.google.maps.routes.v1.VehicleEmissionType result = com.google.maps.routes.v1.VehicleEmissionType.valueOf(emissionType_);
      return result == null ? com.google.maps.routes.v1.VehicleEmissionType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Describes the vehicle's emission type.
     * Applies only to the DRIVE travel mode.
     * </pre>
     *
     * <code>.google.maps.routes.v1.VehicleEmissionType emission_type = 2;</code>
     * @param value The emissionType to set.
     * @return This builder for chaining.
     */
    public Builder setEmissionType(com.google.maps.routes.v1.VehicleEmissionType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      emissionType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Describes the vehicle's emission type.
     * Applies only to the DRIVE travel mode.
     * </pre>
     *
     * <code>.google.maps.routes.v1.VehicleEmissionType emission_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmissionType() {
      
      emissionType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.maps.routes.v1.VehicleInfo)
  }

  // @@protoc_insertion_point(class_scope:google.maps.routes.v1.VehicleInfo)
  private static final com.google.maps.routes.v1.VehicleInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.maps.routes.v1.VehicleInfo();
  }

  public static com.google.maps.routes.v1.VehicleInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VehicleInfo>
      PARSER = new com.google.protobuf.AbstractParser<VehicleInfo>() {
    @java.lang.Override
    public VehicleInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VehicleInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VehicleInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VehicleInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.maps.routes.v1.VehicleInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

