name: Test Actions
on:
  push:
    paths: ['actions/**']
jobs:
  gapic:
    runs-on: ubuntu-latest    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run the gapic action
      uses: ./actions/gapic
      with:
        target: //google/maps/routes/v1:google-maps-routes-v1-java
        github_token: ${{ secrets.GITHUB_TOKEN_REPO }}
        tar_path: google-maps-routes-v1-java
        tar_strip_components: 1
        cache_service_account: ${{ secrets.BAZEL_CACHE_SERVICE_ACCOUNT }}
        ignore: |
          gradle/*
          gradlew
          gradlew.bat
