name: Test Actions
on:
  push:
  schedule:
    - cron:  '0 * * * *'
jobs:
  gapic:
    runs-on: ubuntu-latest    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run the gapic action
      uses: ./actions/gapic
      with:
        target: //google/maps/routes/v1:gapic-maps-routes-v1-go
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tar_path: gapic-maps-routes-v1-go/cloud.google.com/go/maps
        tar_strip_components: 4
        cache_service_account: ${{ secrets.SERVICE_ACCOUNT_CACHE }}
